// Handles raw Spotify API calls using Axios
const axios = require('axios');
const qs = require('qs');

const getSpotifyToken = async (code) => {
  const authHeader = Buffer.from(`${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`).toString('base64');
  
  const response = await axios.post('https://accounts.spotify.com/api/token', 
    qs.stringify({
      grant_type: 'authorization_code',
      code,
      redirect_uri: process.env.SPOTIFY_REDIRECT_URI
    }),
    {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': `Basic ${authHeader}`
      }
    }
  );
  return response.data;
};

const refreshSpotifyToken = async (refreshToken) => {
  const authHeader = Buffer.from(`${process.env.SPOTIFY_CLIENT_ID}:${process.env.SPOTIFY_CLIENT_SECRET}`).toString('base64');
  
  const response = await axios.post('https://accounts.spotify.com/api/token',
    qs.stringify({
      grant_type: 'refresh_token',
      refresh_token: refreshToken
    }),
    {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': `Basic ${authHeader}`
      }
    }
  );
  return response.data;
};

const getPlaylistTracks = async (token, playlistId) => {
  let tracks = [];
  let nextUrl = `https://api.spotify.com/v1/playlists/${playlistId}/tracks?limit=100`;

  while (nextUrl) {
    const response = await axios.get(nextUrl, {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    });
    tracks = tracks.concat(response.data.items);
    nextUrl = response.data.next;
  }

  return tracks;
};

const getArtistGenres = async (token, artistIds) => {
  let allArtists = [];
  
  // Spotify API allows max 50 artists per request
  for (let i = 0; i < artistIds.length; i += 50) {
    const batch = artistIds.slice(i, i + 50).join(',');
    const response = await axios.get(`https://api.spotify.com/v1/artists?ids=${batch}`, {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    });
    allArtists = allArtists.concat(response.data.artists);
  }
  
  // Return an array mapping artist ID to their genres
  return allArtists.map(artist => ({
    id: artist.id,
    genres: artist.genres
  }));
};

const getAudioFeatures = async (token, trackIds) => {
  const map = new Map();
  const BATCH = 100;

  for (let i = 0; i < trackIds.length; i += BATCH) {
    const batch = trackIds.slice(i, i + BATCH);
    const response = await axios.get(`https://api.spotify.com/v1/audio-features?ids=${batch.join(",")}`, {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    });

    for (const f of response.data.audio_features) {
      if (!f) continue;
      map.set(f.id, {
        id: f.id,
        energy: f.energy,
        tempo: f.tempo,
        valence: f.valence,
        danceability: f.danceability,
        acousticness: f.acousticness,
        instrumentalness: f.instrumentalness,
        speechiness: f.speechiness,
        loudness: f.loudness,
      });
    }
  }

  return map;
};

const enrichTracks = async (token, tracks) => {
  const ids = tracks.map((t) => t.track?.id || t.id).filter(id => id);
  const featuresMap = await getAudioFeatures(token, ids);

  return tracks.reduce((acc, track) => {
    const tId = track.track?.id || track.id;
    const features = featuresMap.get(tId);
    if (features) acc.push({ ...track, features });
    return acc;
  }, []);
};

const createPlaylist = async (token, userId, name, trackUris) => {
  const response = await axios.post(`https://api.spotify.com/v1/users/${userId}/playlists`, 
    { name, public: false, description: "Generated by PlaylistFilter" },
    {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      }
    }
  );

  const playlistId = response.data.id;
  const BATCH = 100;

  for (let i = 0; i < trackUris.length; i += BATCH) {
    const batch = trackUris.slice(i, i + BATCH);
    await axios.post(`https://api.spotify.com/v1/playlists/${playlistId}/tracks`,
      { uris: batch },
      {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      }
    );
  }

  return playlistId;
};

const getUserPlaylists = async (token) => {
  const playlists = [];
  let nextUrl = 'https://api.spotify.com/v1/me/playlists?limit=50';

  while (nextUrl) {
    const response = await axios.get(nextUrl, {
      headers: { 'Authorization': `Bearer ${token}` }
    });
    
    for (const p of response.data.items) {
      if (!p) continue;
      playlists.push({
        id: p.id,
        name: p.name,
        trackCount: p.tracks.total,
        image: p.images?.[0]?.url ?? null,
        owner: p.owner.display_name,
      });
    }

    nextUrl = response.data.next;
  }

  return playlists;
};

module.exports = {
  getSpotifyToken,
  refreshSpotifyToken,
  getPlaylistTracks,
  getArtistGenres,
  getAudioFeatures,
  enrichTracks,
  createPlaylist,
  getUserPlaylists
};
